version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-svc
    env_file:
      - .env
    ports:
      - "${PORT:-5000}:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  mongodb:
    image: mongo:3.6
    container_name: usersvc-mongo
    command: ["mongod", "--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-changeme}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--username", "${MONGO_USERNAME:-root}", "--password", "${MONGO_PASSWORD:-changeme}", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo_data:
